### ISSUE TITLE
Recommended Citation

### ISSUE THREAD

**Issue by augustfly** [giacomov/gtburst#1]
Hello,

I am a Data Scientist with the AAS Journals (http://journals.aas.org). We have identified a use of _gtBurst_ in the articles submitted to our Journals (ApJ/AJ). However, you do not provide a recommended citation for this code. 

Per our Journal's Software Policy (http://journals.aas.org/policy/software.html), we are encouraging authors to properly cite code where possible. In this instance we would like to ask if you would provide a recommended citation for _gtBurst_ or to archive _gtBurst_ in a persistent citable way. 

The **GitHub=>Zenodo** workflow provides one way to create a citable unit of software: https://guides.github.com/activities/citable-code/

It would be best to add the recommended citation to the top level of this repository. Thank you for considering this request.

**Comment by giacomov** [comment]
Thanks for your message!

gtburst is part of the official Fermi Science Tools (http://fermi.gsfc.nasa.gov/ssc/data/analysis/documentation/). People usually cite that.

Anyway, following your kind suggestion, I created a Zenodo entry:

https://zenodo.org/record/59783#

thanks!
